# Generated by Django 3.2.16 on 2025-12-05 18:25

import catalog.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0006_auto_20251107_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='banknote',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banknote_items', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='banknote',
            name='height',
            field=models.IntegerField(blank=True, null=True, validators=[catalog.validators.validate_positive_integer], verbose_name='Высота (мм)'),
        ),
        migrations.AddField(
            model_name='banknote',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение предмета', null=True, upload_to='collectibles/%Y/%m/%d/', validators=[catalog.validators.validate_image_size, catalog.validators.validate_image_extension], verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='banknote',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Серийный номер'),
        ),
        migrations.AddField(
            model_name='banknote',
            name='width',
            field=models.IntegerField(blank=True, null=True, validators=[catalog.validators.validate_positive_integer], verbose_name='Ширина (мм)'),
        ),
        migrations.AddField(
            model_name='coin',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coin_items', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='coin',
            name='diameter',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Диаметр в миллиметрах', max_digits=6, null=True, validators=[catalog.validators.validate_positive_decimal], verbose_name='Диаметр (мм)'),
        ),
        migrations.AddField(
            model_name='coin',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение предмета', null=True, upload_to='collectibles/%Y/%m/%d/', validators=[catalog.validators.validate_image_size, catalog.validators.validate_image_extension], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='banknote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='banknote',
            name='currency',
            field=models.CharField(blank=True, default='RUB', max_length=50, null=True, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='banknote',
            name='is_on_main',
            field=models.BooleanField(default=False, verbose_name='На главной странице'),
        ),
        migrations.AlterField(
            model_name='banknote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='banknote',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[catalog.validators.validate_year], verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='currency',
            field=models.CharField(blank=True, default='RUB', help_text='Например RUB, USD, EUR', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='is_on_main',
            field=models.BooleanField(default=False, verbose_name='На главной странице'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='mint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.mint', verbose_name='Монетный двор'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='В граммах', max_digits=8, null=True, validators=[catalog.validators.validate_positive_decimal], verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[catalog.validators.validate_year], verbose_name='Год'),
        ),
    ]
