# Generated by Django 6.0 on 2025-12-05 18:50

import catalog.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20251205_2125'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banknote',
            options={'verbose_name': 'банкнота', 'verbose_name_plural': 'банкноты'},
        ),
        migrations.AlterModelOptions(
            name='coin',
            options={'verbose_name': 'монета', 'verbose_name_plural': 'монеты'},
        ),
        migrations.AlterModelOptions(
            name='mint',
            options={'verbose_name': 'монетный двор', 'verbose_name_plural': 'монетные дворы'},
        ),
        migrations.AlterField(
            model_name='banknote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи'),
        ),
        migrations.AlterField(
            model_name='banknote',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='banknote',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Высота (мм)'),
        ),
        migrations.AlterField(
            model_name='banknote',
            name='image',
            field=models.ImageField(blank=True, upload_to='collectible_images', validators=[catalog.validators.validate_image_size, catalog.validators.validate_image_extension], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='banknote',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина (мм)'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='diameter',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Диаметр в миллиметрах', max_digits=6, null=True, verbose_name='Диаметр (мм)'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='image',
            field=models.ImageField(blank=True, upload_to='collectible_images', validators=[catalog.validators.validate_image_size, catalog.validators.validate_image_extension], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='mint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.mint', verbose_name='Монетный двор'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='В граммах', max_digits=8, null=True, verbose_name='Вес'),
        ),
    ]
