# Generated by Django 5.2.8 on 2025-12-06 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0008_alter_banknote_options_alter_coin_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Личные заметки об этом предмете', verbose_name='Заметки')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('banknote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.banknote', verbose_name='Банкнота')),
                ('coin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.coin', verbose_name='Монета')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'элемент коллекции',
                'verbose_name_plural': 'элементы коллекции',
                'ordering': ['-added_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('coin__isnull', False), ('banknote__isnull', False), _connector='OR'), name='not_both_null'), models.UniqueConstraint(condition=models.Q(('coin__isnull', False)), fields=('user', 'coin'), name='unique_user_coin'), models.UniqueConstraint(condition=models.Q(('banknote__isnull', False)), fields=('user', 'banknote'), name='unique_user_banknote')],
            },
        ),
    ]
